# Generated by Django 4.0.2 on 2022-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_created_by_alter_ticket_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_open',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
